INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Resident Evil', 10.0, 2024, 'Survival Horror', 'PS5', '', '', '')
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Tomb Raider', 9.0, 2023, 'Aventura', 'PS4', '', '', '')
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('FFX', 8.0, 2022, 'RPG', 'PS3', '', '', '')
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Lol', 7.0, 2021, 'Moba', 'PC', '', '', '')
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('007', 6.0, 2020, 'FPS', 'Nintendo 64', '', '', '')
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Last Of Us', 5.0, 2019, 'Survival Horror', 'PS2', '', '', '')
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('WarCraft', 4.0, 2018, 'Moba', 'PS1', '', '', '')
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('GTA', 3.0, 2017, 'Acao/Aventura', 'PSX', '', '', '')
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mario Bros', 2.0, 2016, 'Plataforma', 'Super Nintendo', '', '', '')
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('WarZone', 1.0, 2015, 'FPS', 'PC', '', '', '')